version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    labels:
      - "automerge"
      - "javascript"
      - "dependencies"
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"