name: Deploy website to S3

on:
  pull_request_target:
    types: [closed]
    branches: [master]
    paths:
      - 'src/**'
      - 'astro.config.ts'
      - 'resume/**'
      - 'public/assets/**'
      - 'public/fonts/**'
      - 'public/site.webmanifest'

jobs:
  build-resume:
    name: Build resume
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: ./.github/actions/build-resume
        name: Compile resumes
      - uses: actions/upload-artifact@master
        name: Upload English resume
        with:
          name: lucas-kjaero-zhang-resume.pdf
          path: resume/lucas-kjaero-zhang-resume.pdf
      - uses: actions/upload-artifact@master
        name: Upload Chinese resume
        with:
          name: lucas-kjaero-zhang-resume-chinese.pdf
          path: resume/lucas-kjaero-zhang-个人简历.pdf

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: ./.github/actions/build-frontend

  deploy:
    name: Deploy to S3
    needs: [build-resume, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: website-dist
          path: dist
      - uses: actions/download-artifact@master
        name: Download English resume
        with:
          name: lucas-kjaero-zhang-resume.pdf
          path: dist
      - uses: actions/download-artifact@master
        name: Download Chinese resume
        with:
          name: lucas-kjaero-zhang-resume-chinese.pdf
          path: dist
      - name: Verify website artifact
        run: test -f dist/index.html
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Push to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}/ --no-progress --delete
      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id EWJC89C0ACD7D --paths /index.html /*
