name: Deploy website to S3

on:
  push:
    branches:
    - master

jobs:
  build-resume:
    name: Build resume
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install latex and fonts
      run: sudo apt-get install texlive-xetex fonts-arphic-gbsn00lp fonts-wqy-zenhei fonts-arphic-gkai00mp latex-cjk-all
    - name: Compile English resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-resume.tex
      working-directory: resume
    - name: Compile Chinese resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-个人简历.tex
      working-directory: resume
    - uses: actions/upload-artifact@master
      with:
        name: lucas-kjaero-zhang-resume.pdf
        path: resume/lucas-kjaero-zhang-resume.pdf
    - uses: actions/upload-artifact@master
      with:
        name: lucas-kjaero-zhang-个人简历.pdf
        path: resume/lucas-kjaero-zhang-个人简历.pdf
  
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nuxt/actions-yarn@master
        name: Build dependencies
        with:
          args: install --prod --pure-lockfile
      - uses: nuxt/actions-yarn@master
        with:
          args: addwebpack-bundle-analyzer
      - uses: nuxt/actions-yarn@master
        name: Build production bundle
        with:
          args: run build
      - uses: actions/upload-artifact@master
        with:
          name: gatsby-public
          path: public
  
  deploy: 
    name: Deploy to S3
    needs: [build-resume, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: gatsby-public
          path: public
      - uses: actions/download-artifact@master
        with:
          name: lucas-kjaero-zhang-resume.pdf
          path: public
      - uses: actions/download-artifact@master
        with:
          name: lucas-kjaero-zhang-个人简历.pdf
          path: public
      - uses: jakejarvis/s3-sync-action@master
        name: Push to S3
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: 'public'
