name: Deploy website to S3

on:
  push:
    branches:
    - master

jobs:
  build-resume:
    name: Build resume
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install latex and fonts
      run: sudo apt-get install texlive-xetex fonts-arphic-gbsn00lp fonts-wqy-zenhei fonts-arphic-gkai00mp latex-cjk-all
    - name: Compile English resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-resume.tex
      working-directory: resume
    - name: Compile Chinese resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-个人简历.tex
      working-directory: resume
    - uses: actions/upload-artifact@master
      with:
        name: lucas-kjaero-zhang-resume.pdf
        path: resume/lucas-kjaero-zhang-resume.pdf
    - uses: actions/upload-artifact@master
      with:
        name: lucas-kjaero-zhang-个人简历.pdf
        path: resume/lucas-kjaero-zhang-个人简历.pdf
  
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Install node
        with:
          node-version: '10.x'
      - name: Build dependencies
        run: npm ci --only=production
      - name: Build production bundle
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
        run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: gatsby-public
          path: public
  
  deploy: 
    name: Deploy to S3
    needs: [build-resume, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: gatsby-public
          path: public
      - uses: actions/download-artifact@master
        with:
          name: lucas-kjaero-zhang-resume.pdf
          path: public
      - uses: actions/download-artifact@master
        with:
          name: lucas-kjaero-zhang-个人简历.pdf
          path: public
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Push to S3
        run: aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }}/ --no-progress
      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id EWJC89C0ACD7D --paths /index.html /*
  release: 
    name: Create release
    needs: [build-resume, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/download-artifact@master
        with:
          name: gatsby-public
          path: public
      - uses: actions/download-artifact@master
        with:
          name: lucas-kjaero-zhang-resume.pdf
          path: public
      - uses: actions/download-artifact@master
        with:
          name: lucas-kjaero-zhang-个人简历.pdf
          path: public
      - name: Zip release
        run: zip -r release.zip public
      - name: Upload zip
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releaset.zip
          asset_name: release.zip
          asset_content_type: application/zip
