name: Deploy website to S3

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install latex and fonts
      run: sudo apt-get install texlive-xetex fonts-arphic-gbsn00lp fonts-wqy-zenhei fonts-arphic-gkai00mp latex-cjk-all
    - name: Compile English resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-resume.tex
      working-directory: resume
    - name: Compile Chinese resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-个人简历.tex
      working-directory: resume
    - name: Add resume to build
      run: |
        mv resume/lucas-kjaero-zhang-resume.pdf public/lucas-kjaero-zhang-resume.pdf
        mv resume/lucas-kjaero-zhang-个人简历.pdf public/lucas-kjaero-zhang-个人简历.pdf
    - uses: jakejarvis/s3-sync-action@master
      name: Push to S3
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'
        SOURCE_DIR: 'public'
