name: PR Build

on:
  schedule:
    - cron:  '0 9 * * *'
  
jobs:
  verify-site-is-up:
    name: "Verify site is up"
    runs-on: ubuntu-latest
    steps:
      - name: Check main page
        run: curl https://www.lucaskjaerozhang.com/
      - name: Check resumes
        run: |
          curl https://www.lucaskjaerozhang.com/lucas-kjaero-zhang-resume.pdf
          curl https://www.lucaskjaerozhang.com/lucas-kjaero-zhang-%E4%B8%AA%E4%BA%BA%E7%AE%80%E5%8E%86.pdf

  check-links:
    name: "Check links"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check links
        run: python link_checker.py