name: Prepare pull request
on:
  pull_request

jobs:
  add-label:
    name: Apply patch label to pull request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
