name: Create release

on:
  pull_request:
    types: closed
    branches: master

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release
    steps:
    - name: Create release
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
