name: PR Check - Javascript and Content

on: 
  pull_request:
    paths:
      - "*.js"
      - "**/*.js"
      - "content/*"
      - "src/*"

jobs:
  build-frontend:
    name: Test that frontend builds
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.4
        name: Install node
        with:
          node-version: '12.x'
      - name: Build dependencies
        run: npm ci --only=production
      - name: Build production bundle
        env:
          CI: true
        run: npm run build
      - uses: actions/upload-artifact@master
        name: Upload website content
        with:
          name: gatsby-public
          path: public

  test:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.4
        name: Install node
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm install
      - name: End to end test
        run: npm test
      - name: Lint
        run: npm run lint
  
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  deploy:
    name: Deploy to dev environment
    needs: [build-frontend, security]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: gatsby-public
          path: public
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Push to S3
        run: aws s3 sync public s3://${{ secrets.AWS_DEV_S3_BUCKET }}/ --no-progress --delete
      - name: Echo dev address
        run: echo "http://lucas-kjaero-zhang-website-dev.s3-website-us-west-1.amazonaws.com"