name: PR Check - Dependencies

on: 
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"

jobs:
  build-frontend:
    name: Test that frontend builds
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.4
        name: Install node
        with:
          node-version: '15.x'
      - name: Build dependencies
        run: npm ci --only=production
      - name: Build production bundle
        env:
          CI: true
        run: npm run build
      - uses: actions/upload-artifact@master
        name: Upload website content
        with:
          name: gatsby-public
          path: public
  
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.4
      name: Install node
      with:
        node-version: '15.x'
    - name: Build dependencies
      run: npm ci --only=production
    - name: Validate security of dependencies
      run: npx audit-ci --moderate -a 1550 -a 1500 -a 786
  
  test:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.4
        name: Install node
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: npm install
      - name: End to end test
        run: npm test
      - name: Lint
        run: npm run lint