name: PR Check - Code

on: [pull_request]

jobs:
  actions:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: raven-actions/actionlint@v2

  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/check-links
  
  build-frontend:
    name: Test that frontend production bundle builds
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/build-frontend
  
  test:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/setup-node
        name: Install node
      - name: Install dependencies
        run: npm ci
      - name: End to end test
        run: npm test
      - name: Lint
        run: npm run lint
  
  code-security:
    name: Code security scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: ${{ matrix.language }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
