name: PR Check - Resume

on: 
  pull_request:
    paths:
      - "resume/*"

jobs:
  build-resume:
    name: Test that resumes build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latex and fonts
      run: sudo apt-get install texlive-xetex fonts-arphic-gbsn00lp fonts-wqy-zenhei fonts-arphic-gkai00mp latex-cjk-all
    - name: Compile English resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-resume.tex
      working-directory: resume
    - name: Compile Chinese resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-个人简历.tex
      working-directory: resume
    - uses: actions/upload-artifact@master
      name: Upload English resume
      with:
        name: lucas-kjaero-zhang-resume.pdf
        path: resume/lucas-kjaero-zhang-resume.pdf
    - uses: actions/upload-artifact@master
      name: Upload Chinese resume
      with:
        name: lucas-kjaero-zhang-resume-chinese.pdf
        path: resume/lucas-kjaero-zhang-个人简历.pdf