name: PR Check - Code

on: [pull_request]

jobs:
  actions:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: raven-actions/actionlint@v2

  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.13.2
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.13.2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check links
        run: python link_checker.py
  
  build-frontend:
    name: Test that frontend production bundle builds
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/setup-node
        name: Install node
      - name: Build dependencies
        run: npm ci
      - name: Build production bundle
        env:
          CI: true
        run: npm run build
      - uses: actions/upload-artifact@master
        name: Upload website content
        with:
          name: website-dist
          path: dist
  
  test:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/setup-node
        name: Install node
      - name: Install dependencies
        run: npm ci
      - name: End to end test
        run: npm test
      - name: Lint
        run: npm run lint
  
  code-security:
    name: Code security scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: ${{ matrix.language }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
