name: PR Build

on: [pull_request]

jobs:
  add-label:
    name: Add patch label to pull request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  build-frontend:
    name: "Test that frontend builds"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Install node
        with:
          node-version: '10.x'
      - name: Build dependencies
        run: npm ci --only=production
      - name: Build production bundle
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
        run: npm run build
  
  build-resume:
    name: "Test that resumes build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install latex and fonts
      run: sudo apt-get install texlive-xetex fonts-arphic-gbsn00lp fonts-wqy-zenhei fonts-arphic-gkai00mp latex-cjk-all
    - name: Compile English resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-resume.tex
      working-directory: resume
    - name: Compile Chinese resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-个人简历.tex
      working-directory: resume
        
  test-frontend:
    name: "Lint and test frontend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Install node
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm install
      - name: Validate security of dependencies
        run: npx audit-ci --moderate
      - name: End to end test
        run: npm test
      - name: Lint
        run: npm run lint
