name: PR Check - Resume

on: 
  pull_request:
    paths:
      - "resume/*"

jobs:
  build-resume:
    name: Test that resumes build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/build-resume
      name: Compile resumes
    - uses: actions/upload-artifact@v6
      name: Upload resume previews
      with:
        name: resume-previews
        path: |
          resume/lucas-kjaero-zhang-resume.pdf
          resume/lucas-kjaero-zhang-个人简历.pdf
        if-no-files-found: error
