name: PR Build

on: [pull_request]

jobs:
  add-label:
    name: Add patch label to pull request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  build-frontend:
    name: "Test that frontend builds"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Install node
        with:
          node-version: '12.x'
      - name: Build dependencies
        run: npm ci --only=production
      - name: Validate security of dependencies
        run: npx audit-ci --moderate -a 1550
      - name: Build production bundle
        env:
          CI: true
        run: npm run build
      - uses: actions/upload-artifact@master
        name: Upload website content
        with:
          name: gatsby-public
          path: public

  build-resume:
    name: "Test that resumes build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install latex and fonts
      run: sudo apt-get install texlive-xetex fonts-arphic-gbsn00lp fonts-wqy-zenhei fonts-arphic-gkai00mp latex-cjk-all
    - name: Compile English resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-resume.tex
      working-directory: resume
    - name: Compile Chinese resume
      run: xelatex -file-line-error -interaction=nonstopmode -recorder lucas-kjaero-zhang-个人简历.tex
      working-directory: resume
    - uses: actions/upload-artifact@master
      name: Upload English resume
      with:
        name: lucas-kjaero-zhang-resume.pdf
        path: resume/lucas-kjaero-zhang-resume.pdf
    - uses: actions/upload-artifact@master
      name: Upload Chinese resume
      with:
        name: lucas-kjaero-zhang-resume-chinese.pdf
        path: resume/lucas-kjaero-zhang-个人简历.pdf

  test-frontend:
    name: "Lint and test frontend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Install node
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm install
      - name: Validate security of dependencies
        run: npx audit-ci --moderate -a 1550
      - name: End to end test
        run: npm test
      - name: Lint
        run: npm run lint
  
  check-links:
    name: "Check links"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check links
        run: python link_checker.py

  deploy:
    name: Deploy to dev environment
    needs: [build-resume, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: gatsby-public
          path: public
      - uses: actions/download-artifact@master
        name: Download English resume
        with:
          name: lucas-kjaero-zhang-resume.pdf
          path: public
      - uses: actions/download-artifact@master
        name: Download Chinese resume
        with:
          name: lucas-kjaero-zhang-resume-chinese.pdf
          path: public
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Push to S3
        run: aws s3 sync public s3://${{ secrets.AWS_DEV_S3_BUCKET }}/ --no-progress --delete
      - name: Echo dev address
        run: echo "http://lucas-kjaero-zhang-website-dev.s3-website-us-west-1.amazonaws.com"

  verify-site-is-up:
    name: "Verify site is up"
    runs-on: ubuntu-latest
    steps:
      - name: Check main page
        run: curl https://www.lucaskjaerozhang.com/
      - name: Check resumes
        run: |
          curl https://www.lucaskjaerozhang.com/lucas-kjaero-zhang-resume.pdf
          curl https://www.lucaskjaerozhang.com/lucas-kjaero-zhang-%E4%B8%AA%E4%BA%BA%E7%AE%80%E5%8E%86.pdf
      - name: Break
        run: curl https://sfsdfsdfsdfsdfsdfsdffdsfds.com